### ISSUE TITLE
elixir.config.addIngredient() Fails With "Not a function" Error

### ISSUE THREAD

**Issue by tonyjunkes** [Ortus-Solutions/coldbox-elixir#18]
When trying to add an ingredient in my `webpack.config.js`, I receive an error in the console that `elixir.config.addIngredient` is not a function. I receive this error whether the ingredient actually does something or not. Logging `elixir.config` to the console only shows the constructor parameter values available but, I'm not sure if I'd be able to see a static method by doing that anyway.

A workaround in my situation is to use `mergeConfig` to set up the plugin I'm using but, I would like to use this feature for other scenarios too.

**Error and stack trace:**

>C:\dev-test\node_modules\webpack-cli\bin\cli.js:93
>
>TypeError: elixir.config.addIngredient is not a function
    at Object.<anonymous> (C:\dev-test\webpack.config.js:25:15)
    at Module._compile (C:\dev-test\node_modules\v8-compile-cache\v8-compile-cache.js:194:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (C:\dev-test\node_modules\v8-compile-cache\v8-compile-cache.js:161:20)
    at WEBPACK_OPTIONS (C:\dev-test\node_modules\webpack-cli\bin\utils\convert-argv.js:114:13)
    at requireConfig (C:\dev-test\node_modules\webpack-cli\bin\utils\convert-argv.js:116:6)
    at C:\dev-test\node_modules\webpack-cli\bin\utils\convert-argv.js:123:17
    at Array.forEach (<anonymous>)
    at module.exports (C:\dev-test\node_modules\webpack-cli\bin\utils\convert-argv.js:121:15)
    at yargs.parse (C:\dev-test\node_modules\webpack-cli\bin\cli.js:71:45)
    at Object.parse (C:\dev-test\node_modules\yargs\yargs.js:576:18)
    at C:\dev-test\node_modules\webpack-cli\bin\cli.js:49:8
    at Object.<anonymous> (C:\dev-test\node_modules\webpack-cli\bin\cli.js:366:3)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (C:\dev-test\node_modules\webpack\bin\webpack.js:156:2)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)

**Comment by jclausen** [comment]
Not sure why this is still hanging about without a reply.  `mergeConfig` is the way this should be handled in the current iteration.  Otherwise there could be collisions in the config.  The reason for the error you are/were seeing is [described here](https://stackoverflow.com/questions/70876186/nodejs-static-function-is-not-a-function).

If you have ingredients you would like to add, please PR them.  We would be happy to add on.
