### ISSUE TITLE
mix functions: arrays of files vs. single files

### ISSUE THREAD

**Issue by DiscountDarcy** [Ortus-Solutions/coldbox-elixir#5]
This page suggests that you can provide an array of files to functions like mix.css() or mix.js():

https://coldbox-elixir.ortusbooks.com/working_with_stylesheets

But if you do provide an array, this is the result:

`PS F:\dev\inleague> npx webpack
F:\dev\inleague\node_modules\webpack-cli\bin\cli.js:93
                                throw err;
                                ^
TypeError: name.split is not a function
    at ElixirConfig.withoutExtension (F:\dev\inleague\node_modules\coldbox-elixir\src\config\config.js:181:14)
    at ElixirConfig.module.exports [as css] (F:\dev\inleague\node_modules\coldbox-elixir\src\config\ingredients\css.js:8:21)
    at F:\dev\inleague\webpack.config.js:30:9
    at elixir (F:\dev\inleague\node_modules\coldbox-elixir\src\index.js:6:5)
    at Object.<anonymous> (F:\dev\inleague\webpack.config.js:29:18)`

**Comment by DiscountDarcy** [comment]
This also happens if you use a named argument struct, e.g.

`  mix.vue( {
        "filename" : "main.js",
        "options" : {
            "name" : "argon-dashboard",
            "entryDirectory" : "./resources/vue-argon-dashboard-master/src"
        } 
    } );`

**Comment by jclausen** [comment]
This should be resolved in the current version. We use arrays of files quite often to merge multiple stylesheets in to a single file.
